const PDFDocument = require("pdfkit");

/**
 * Generates a professional Incident Report PDF
 * @param {Object} incident - The incident object from Prisma
 * @returns {Promise<Buffer>}
 */
async function generateIncidentReport(incident) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    // --- Header ---
    doc
      .fillColor("#ff3b5c")
      .fontSize(24)
      .text("SENTINEL", { align: "right" })
      .fontSize(10)
      .fillColor("#666")
      .text("Rapid Crisis Intelligence Operations", { align: "right" })
      .moveDown(2);

    doc
      .strokeColor("#eee")
      .lineWidth(1)
      .moveTo(50, 110)
      .lineTo(545, 110)
      .stroke();

    // --- Title ---
    doc
      .moveDown(3)
      .fillColor("#000")
      .fontSize(18)
      .text(`INCIDENT REPORT: #${incident.id.toString().slice(-6).toUpperCase()}`, {
        underline: true,
      })
      .moveDown(1);

    // --- Details Table ---
    const startY = doc.y;
    const col1 = 50;
    const col2 = 200;

    const addRow = (label, value, isCritical = false) => {
      doc
        .fontSize(10)
        .fillColor("#888")
        .text(label, col1, doc.y, { width: 140 })
        .fillColor(isCritical ? "#ff3b5c" : "#000")
        .fontSize(11)
        .text(value, col2, doc.y - 10)
        .moveDown(1);
    };

    addRow("Incident Type:", incident.type);
    addRow("Current Status:", incident.status);
    addRow("Severity Level:", incident.severity, incident.severity === "CRITICAL");
    addRow("Location:", incident.location);
    addRow("Timestamp:", new Date(incident.createdAt).toLocaleString());
    
    doc.moveDown(1);

    // --- AI Analysis ---
    if (incident.metadata) {
      const triage = JSON.parse(incident.metadata);
      doc
        .fontSize(12)
        .fillColor("#ff3b5c")
        .text("AI TRIAGE ANALYSIS", { characterSpacing: 1 })
        .moveDown(0.5);

      doc
        .fontSize(10)
        .fillColor("#333")
        .rect(col1, doc.y, 495, 80)
        .fill("#f9f9f9")
        .stroke("#eee")
        .fillColor("#000")
        .text(`Summary: ${triage.summary || "N/A"}`, col1 + 10, doc.y + 10)
        .moveDown(0.5)
        .text(`Classification: ${triage.classification || "N/A"}`, col1 + 10)
        .moveDown(0.5)
        .text(`Protocol: ${triage.response_protocol ? triage.response_protocol.join(" -> ") : "N/A"}`, col1 + 10, doc.y, { width: 470 });
    }

    doc.moveDown(5);

    // --- Footer ---
    const pageHeight = doc.page.height;
    doc
      .fontSize(8)
      .fillColor("#aaa")
      .text(
        "CONFIDENTIAL - Generated by Sentinel RCIO System. Verified by Vision Hack 2026 Audit Engine.",
        50,
        pageHeight - 70,
        { align: "center", width: 495 }
      );

    doc.end();
  });
}

module.exports = { generateIncidentReport };
